import Link from "next/link";
import { FileText } from "lucide-react";

export const metadata = { title: "Terms of Service | AI Career Simulator" };

export default function TermsPage() {
  return (
    <div className="min-h-full w-full bg-slate-50">
      <div className="mx-auto w-full max-w-3xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8">
        <div className="text-center">
          <span className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600">
            <FileText className="h-6 w-6" />
          </span>
          <h1 className="mt-3 text-2xl font-bold text-slate-900 sm:text-3xl">Terms of Service</h1>
          <p className="mt-2 text-sm text-slate-500">Last updated September 12, 2026</p>
        </div>

        <div className="mt-10 flex flex-col gap-8 text-sm leading-relaxed text-slate-700">
          <section>
            <h2 className="text-base font-semibold text-slate-900">Using the Service</h2>
            <p className="mt-2">
              This platform provides AI-generated, interactive career simulations for educational
              exploration. Simulation content, scoring, and feedback are generated by an AI model and are
              intended to support career exploration and skill-building. They are not a certification,
              guarantee of professional aptitude, or substitute for professional career counseling.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">Accounts</h2>
            <p className="mt-2">
              You may use the service without an account, in which case your simulation history is tied
              to an anonymous identifier stored in your browser and is not portable across devices.
              Creating an account lets you access your simulation history and reports from any device.
              You are responsible for keeping your account credentials secure and for all activity under
              your account.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">Acceptable Use</h2>
            <p className="mt-2">
              You agree not to misuse the service: no attempting to disrupt the platform, no scraping or
              automated bulk extraction of simulation content, and no submitting unlawful, harmful, or
              abusive content into any simulation input field.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">Intellectual Property</h2>
            <p className="mt-2">
              The simulation scenarios, scoring rubrics, and platform design are owned by us. Reports you
              generate from your own completed simulations are yours to keep, download, and share.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">No Warranty</h2>
            <p className="mt-2">
              The service is provided &quot;as is.&quot; AI-generated scenarios and scores may contain
              inaccuracies; we do not warrant that feedback is error-free or that it reflects any
              particular employer&apos;s hiring standards.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">Changes</h2>
            <p className="mt-2">
              We may update these terms from time to time. Continued use of the service after a change
              constitutes acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900">Contact</h2>
            <p className="mt-2">
              Questions about these terms can be sent through the{" "}
              <Link href="/#contact" className="font-medium text-indigo-600 hover:text-indigo-700">
                contact form
              </Link>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
